# Generated by Django 3.0.4 on 2020-05-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电影ID')),
                ('movie_imdbId', models.CharField(max_length=200, verbose_name='imdb号')),
                ('movie_title', models.CharField(max_length=200, verbose_name='电影标题')),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='电影评分')),
                ('movie_img', models.CharField(max_length=500, null=True, verbose_name='海报')),
                ('pop', models.IntegerField(default=0, verbose_name='观看人数')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('movie_id', models.IntegerField(verbose_name='电影id')),
                ('movie_imdbId', models.CharField(max_length=200, verbose_name='imdb号')),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='电影评分')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户Id')),
                ('movie_id', models.IntegerField(null=True, verbose_name='电影Id')),
                ('movie_imdbId', models.IntegerField(null=True, verbose_name='imdbId')),
                ('movie_title', models.CharField(max_length=100, verbose_name='电影标题')),
                ('movie_img', models.CharField(max_length=500, verbose_name='电影图片')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'F'), ('female', 'M')], default='M', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_genres', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Movie')),
            ],
        ),
    ]
