# Generated by Django 3.0.4 on 2020-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='movie_imdbId',
            field=models.CharField(max_length=100, null=True, verbose_name='imdbId'),
        ),
    ]
