# Generated by Django 3.0.4 on 2020-06-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200601_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
